# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyagent" do
  version "0.5.2"

  on_macos do
    on_intel do
      sha256 "8ffc14c1e722e55a3a75d0c63800940377c23b2e41caa8a4ab6b525b556a26ee"
      url "https://github.com/chojs23/lazyagent/releases/download/v#{version}/lazyagent_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c5b68e743b5361a75ff745b36f50af6014e133819fc60fc2b64f3ba30bf3396f"
      url "https://github.com/chojs23/lazyagent/releases/download/v#{version}/lazyagent_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fa79dad6c71e446c53b6def883ff48f38f190b167c3f95173a66bdef5ad81b7c"
      url "https://github.com/chojs23/lazyagent/releases/download/v#{version}/lazyagent_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "94f6587a669e397f015764c9e9b8c8c5343e2051118fe96ed52cf83205bf8072"
      url "https://github.com/chojs23/lazyagent/releases/download/v#{version}/lazyagent_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lazyagent"
  desc "Observe your ai agents and sessions from the terminal"
  homepage "https://github.com/chojs23/lazyagent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyagent"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazyagent"]
    end
  end

  # No zap stanza required

end
